### ISSUE TITLE
Reversed Pattern P2P crashes server

### ISSUE THREAD

**Issue by KillerOfPie** [Monifactory/MAE2#2]
Replicate: Set the Pattern P2P on a Molecular assembler as the input and 2 Pattern P2Ps on Pattern Providers as the outputs, then send an Autocraft that either of the providers handle

I was using Extended Assembler and Provider from ExtendedAE but I assume this would also happen with standard providers

```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2024-06-28 16:34:26
Description: Ticking grid on end of server tick

java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "positions" is null
	at appeng.helpers.patternprovider.PatternProviderLogic.pushPattern(PatternProviderLogic.java:977) ~[appliedenergistics2-forge-15.2.2.jar%23622!/:15.2.2] {re:mixin,re:classloading,pl:mixin:APP:mixins.mae2.json:PatternProviderLogicMixin,pl:mixin:APP:mixins.appflux.json:MixinPatternProviderLogic,pl:mixin:A}
	at appeng.crafting.execution.CraftingCpuLogic.executeCrafting(CraftingCpuLogic.java:211) ~[appliedenergistics2-forge-15.2.2.jar%23622!/:15.2.2] {re:classloading}
	at appeng.crafting.execution.CraftingCpuLogic.tickCraftingLogic(CraftingCpuLogic.java:156) ~[appliedenergistics2-forge-15.2.2.jar%23622!/:15.2.2] {re:classloading}
	at appeng.me.service.CraftingService.onServerEndTick(CraftingService.java:152) ~[appliedenergistics2-forge-15.2.2.jar%23622!/:15.2.2] {re:classloading}
	at appeng.me.Grid.onServerEndTick(Grid.java:236) ~[appliedenergistics2-forge-15.2.2.jar%23622!/:15.2.2] {re:classloading}
	at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:325) ~[appliedenergistics2-forge-15.2.2.jar%23622!/:15.2.2] {re:classloading}
	at appeng.hooks.ticking.TickHandler.onServerTick(TickHandler.java:299) ~[appliedenergistics2-forge-15.2.2.jar%23622!/:15.2.2] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:950) ~[forge-1.20.1-47.2.20-universal.jar%231072!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.potential_spawns_alloc.ForgeEventFactoryMixin,pl:mixin:APP:aether.mixins.json:common.ForgeEventFactoryMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:835) ~[server-1.20.1-20230612.114412-srg.jar%231067!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%231067!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%231067!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mods: 
	Applied Energistics 2 (ae2), Version: 15.2.2
		Issue tracker URL: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues
		at TRANSFORMER/ae2@15.2.2/appeng.helpers.patternprovider.PatternProviderLogic.pushPattern(PatternProviderLogic.java:977)

	Modern AE2 Additions (mae2), Version: 1.1.0
		Mixin class: stone.mae2.mixins.PatternProviderLogicMixin
		Target: appeng.helpers.patternprovider.PatternProviderLogic
		at TRANSFORMER/ae2@15.2.2/appeng.helpers.patternprovider.PatternProviderLogic.pushPattern(PatternProviderLogic.java:977)
Stacktrace:
	at appeng.helpers.patternprovider.PatternProviderLogic.pushPattern(PatternProviderLogic.java:977) ~[appliedenergistics2-forge-15.2.2.jar%23622!/:15.2.2] {re:mixin,re:classloading,pl:mixin:APP:mixins.mae2.json:PatternProviderLogicMixin,pl:mixin:APP:mixins.appflux.json:MixinPatternProviderLogic,pl:mixin:A}
	at appeng.crafting.execution.CraftingCpuLogic.executeCrafting(CraftingCpuLogic.java:211) ~[appliedenergistics2-forge-15.2.2.jar%23622!/:15.2.2] {re:classloading}
	at appeng.crafting.execution.CraftingCpuLogic.tickCraftingLogic(CraftingCpuLogic.java:156) ~[appliedenergistics2-forge-15.2.2.jar%23622!/:15.2.2] {re:classloading}
	at appeng.me.service.CraftingService.onServerEndTick(CraftingService.java:152) ~[appliedenergistics2-forge-15.2.2.jar%23622!/:15.2.2] {re:classloading}
	at appeng.me.Grid.onServerEndTick(Grid.java:236) ~[appliedenergistics2-forge-15.2.2.jar%23622!/:15.2.2] {re:classloading}
-- Grid being ticked --
Details:
	Nodes: 1163
	Serial number: 819
	Node: node@56470562 hosted by appeng.parts.networking.SmartCablePart @ -17657,45,13459
	Part Side: ~~NULL~~
	Name: ae2:cable_bus // appeng.blockentity.networking.CableBusBlockEntity
	Block: CableBusBlock[cable_bus][light_level=0,waterlogged=false]
	Block location: World: (-17657,45,13459), Section: (at 7,13,3 in -1104,2,841; chunk contains blocks -17664,-64,13456 to -17649,319,13471), Region: (-35,26; contains chunks -1120,832 to -1089,863, blocks -17920,-64,13312 to -17409,319,13823)
	Block: CableBusBlock[cable_bus][light_level=0,waterlogged=false]
	Block location: World: (-17657,45,13459), Section: (at 7,13,3 in -1104,2,841; chunk contains blocks -17664,-64,13456 to -17649,319,13471), Region: (-35,26; contains chunks -1120,832 to -1089,863, blocks -17920,-64,13312 to -17409,319,13823)
	Block Entity NBT: {ForgeCaps:{},cable:{gn:{e:25.0d,p:1},id:"ae2:white_smart_cable"},east:{freq:-20224s,gn:{e:25.0d,p:1},id:"mae2:pattern_p2p_tunnel",output:1b},hasRedstone:2}
	Level: ResourceKey[minecraft:dimension / minecraft:overworld]
Stacktrace:
	at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:325) ~[appliedenergistics2-forge-15.2.2.jar%23622!/:15.2.2] {re:classloading}
	at appeng.hooks.ticking.TickHandler.onServerTick(TickHandler.java:299) ~[appliedenergistics2-forge-15.2.2.jar%23622!/:15.2.2] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:950) ~[forge-1.20.1-47.2.20-universal.jar%231072!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.potential_spawns_alloc.ForgeEventFactoryMixin,pl:mixin:APP:aether.mixins.json:common.ForgeEventFactoryMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:835) ~[server-1.20.1-20230612.114412-srg.jar%231067!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%231067!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%231067!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
```

**Comment by SamStone1000** [comment]
Sorry for not responding sooner but this his was fixed at some point while developing the multi p2ps. v1.3 should have this and any other NPEs with pattern p2ps fixed
